language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mpoghosyan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true mpoghosyan/react-test npm test -- --coverage

after_success:
    # Build all images
    - docker build -t mpoghosyan/multi-client:latest ./client
    - docker build -t mpoghosyan/multi-nginx:latest ./nginx
    - docker build -t mpoghosyan/multi-server:latest ./server
    - docker build -t mpoghosyan/multi-worker:latest ./worker

    # Login to Docker CLI
    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
    
    # Push these images to dockerhub
    - docker push mpoghosyan/multi-client:latest
    - docker push mpoghosyan/multi-nginx:latest
    - docker push mpoghosyan/multi-server:latest
    - docker push mpoghosyan/multi-worker:latest

# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker2-env
    bucket_name: elasticbeanstalk-us-east-2-897526472504
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY