sudo: required
services:
    - docker

before_install:
    - docker build -t mikayelp/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run mikayelp/react-test npm test -- --coverage

after_success:
    - docker build -t mikayelp/multi-client ./client
    - docker build -t mikayelp/multi-nginx ./nginx
    - docker build -t mikayelp/multi-server ./server
    - docker build -t mikayelp/multi-worker ./worker

    # Login to Docker CLI
    - docker login -e="$docker_email" -u="$docker_id" -p="$docker_password"
    
    # Push these images to dockerhub
    - docker push mikayelp/multi-client
    - docker push mikayelp/multi-nginx
    - docker push mikayelp/multi-server
    - docker push mikayelp/multi-worker