language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mpoghosyan/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true mpoghosyan/react-test npm test -- --coverage

after_success:
    # Build all images
    - docker build -t mpoghosyan/multi-client ./client
    - docker build -t mpoghosyan/multi-nginx ./nginx
    - docker build -t mpoghosyan/multi-server ./server
    - docker build -t mpoghosyan/multi-worker ./worker

    # Login to Docker CLI
    - docker login -e="$docker_email" -u="$docker_id" -p="$docker_password"
    
    # Push these images to dockerhub
    - docker push mpoghosyan/multi-client
    - docker push mpoghosyan/multi-nginx
    - docker push mpoghosyan/multi-server
    - docker push mpoghosyan/multi-worker